In [1]:
pip install numpy

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------------- ------------------ 30.7/61.0 kB 660.6 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 651.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 960.0 kB/s eta 0:00:17
   ---------------------------------------- 0.1/15.8 MB 648.1 kB/s eta 0:00:25
   ---------------------------------------- 0.2/15.8 MB 1.2 MB/s eta 0:00:13
    --------------------------------------- 0.3/15.8 MB 1.6 MB/s eta 0:00:10
   - -------------------------------------- 0.4/15.8 MB 2.0 MB/s eta 0:00:08
   - -------------------------------------- 0.5/15.8 MB 2.0 MB/s eta 0:00:08
   - -------------------------------------- 0.6/15.8 MB 1.9 MB/s eta 0:00:09
   -- ------------------------------------- 0.8/15.8 MB 2.2 MB/s eta 0:00:07
   -- ------------------------------------- 0.9/15.8 MB 2.2 MB/s eta 0:00:07
 

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [5]:
random_int_array = np.random.randint(1, 10, size=(3, 3))

In [4]:
random_int_array.dtype

dtype('int32')

In [7]:
np.ndim(random_int_array)

2

In [8]:
random_int_array2 = np.random.randint(10, 100, size=(2, 5))

In [9]:
random_int_array2 

array([[10, 52, 85, 41, 92],
       [50, 32, 63, 52, 45]])

In [10]:
random_int_array2 .shape

(2, 5)

In [12]:
random_int_array3 = np.random.randint(1, 10,10)
random_int_array3


array([7, 7, 8, 1, 5, 1, 2, 4, 1, 1])

In [13]:
np.mean(random_int_array3)

3.7

In [17]:
array2 = np.random.randint(10, 100, size=(2, 5))
array3 = np.random.randint(10, 100, size=(2, 5))
print(ab)
ab=np.add(array2,array3 )

np.mean(ab )

[[ 84  45 135  97 136]
 [106  98  99 111 143]]


125.0

In [19]:
arr= np.random.randint(1, 100,20)
condi=arr>20
filter=arr[condi]
filter

array([46, 81, 69, 82, 93, 54, 38, 74, 99, 85, 39, 49, 60, 44, 63, 72, 54,
       48])

In [20]:
arr2 = [1,2,3,4,5,6,7,8,9,10]
np.random.shuffle(arr2)
arr2

[6, 8, 10, 5, 2, 3, 4, 7, 1, 9]